version: '3'
services:
  resilience4j_app:
    build: .
    network_mode: "host"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: "host"
    env_file:
      - ./docker/grafana.env

